// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcoEF_Xrp4rr3POf1blhTWOq9V4RlvsHA',
    appId: '1:890128029495:web:46bd8f2834e26c97f3ecb2',
    messagingSenderId: '890128029495',
    projectId: 'simple-erp-2026',
    authDomain: 'simple-erp-2026.firebaseapp.com',
    storageBucket: 'simple-erp-2026.firebasestorage.app',
    measurementId: 'G-LGDJS7FYQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN3VmEfBDeYrqjpR_MODfUuRqDXXNAc7Y',
    appId: '1:890128029495:android:027056f2abc7ced6f3ecb2',
    messagingSenderId: '890128029495',
    projectId: 'simple-erp-2026',
    storageBucket: 'simple-erp-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcoEF_Xrp4rr3POf1blhTWOq9V4RlvsHA',
    appId: '1:890128029495:web:5790f805e35c24f0f3ecb2',
    messagingSenderId: '890128029495',
    projectId: 'simple-erp-2026',
    authDomain: 'simple-erp-2026.firebaseapp.com',
    storageBucket: 'simple-erp-2026.firebasestorage.app',
    measurementId: 'G-M8NV4RVG98',
  );
}
